/*
 * ESLint Flat Config
 * @generated by @robot-admin/git-standards
 *
 * 直接修改此文件即可自定义 ESLint 规则
 */
import pluginVue from 'eslint-plugin-vue'
import {
  defineConfigWithVueTs,
  vueTsConfigs,
} from '@vue/eslint-config-typescript'
import jsdocPlugin from 'eslint-plugin-jsdoc'

export default defineConfigWithVueTs(
  //MARK: 基础配置组
  {
    name: "app/files-to-lint",
    files: ["**/*.{js,ts,mts,tsx,vue}"],
  },

  {
    name: "app/files-to-ignore",
    ignores: ["**/dist/**", "**/dist-ssr/**", "**/coverage/**", "__tests__/**"],
  },

  //MARK: 核心规则组（按优先级排序）

  //! 忽略转义字符
  {
    rules: {
      "no-useless-escape": "off",
    },
  },

  pluginVue.configs["flat/essential"], // Vue 专用规则
  vueTsConfigs.recommended, // TS 专用规则

  //MARK: 文件类型覆盖规则

  //! 变量使用规则
  {
    files: ["**/*.js"],
    rules: {
      "no-unused-vars": "error",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    files: ["**/*.{ts,mts,tsx,vue}"],
    rules: {
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": "error",
    },
  },

  //MARK: 自定义规则组（优先级最高）
  {
    plugins: {
      jsdoc: jsdocPlugin,
    },
    rules: {
      //! JSDoc 注释规则
      "jsdoc/require-jsdoc": [
        "warn",
        {
          publicOnly: true,
          require: {
            FunctionDeclaration: true,
            MethodDefinition: false,
            ClassDeclaration: true,
            ArrowFunctionExpression: false,
            FunctionExpression: false,
          },
        },
      ],

      //! 关闭与 oxlint 重复的 ESLint 规则
      "no-undef": "off",

      //! 引号规范（@typescript-eslint/quotes 已在 ESLint 10 移除）
      "vue/html-quotes": ["error", "double"],

      //! TypeScript 安全
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/ban-ts-comment": [
        "error",
        {
          "ts-ignore": "allow-with-description",
        },
      ],

      //! 表达式规范
      "@typescript-eslint/no-unused-expressions": [
        "error",
        {
          allowShortCircuit: true,
          allowTernary: false,
          allowTaggedTemplates: false,
          enforceForJSX: true,
        },
      ],

      //! 代码复杂度
      "max-depth": ["error", 4],
      complexity: ["warn", 10],

      //! 异步代码规范（分片上传等场景需要 await-in-loop）
      "no-await-in-loop": "warn",

      // Vue 规范
      // Vue 组件规则（库项目无 SFC，仅保留通用规则）
      "vue/multi-word-component-names": "off",

      //MARK: 格式规范
      "no-irregular-whitespace": "error",
      "no-multi-spaces": "error",
      "space-infix-ops": "error",
      "array-bracket-spacing": ["error", "never"],
      "arrow-spacing": ["error", { before: true, after: true }],
      "max-params": ["warn", 6],
      "no-eval": "error",
      "prefer-const": "warn",
      "no-var": "warn",
      "prefer-destructuring": [1, { object: true, array: false }],
      "no-duplicate-imports": "error",
    },
  },

  //MARK: ESLINT 白名单配置组
  {
    name: "app/ignore-assets",
    ignores: [
      "src/assets/images/**/*",
      "**/*.d.ts",
      "**/auto-imports.d.ts",
      "src/views/**/components/*.vue",
      "scripts/**/*",
    ],
  },
);
